---
version: '2.1'

services:
  ssh_scan:
    image: jumanjiman/ssh_scan
    build:
      context: src/
      args:
        CI_BUILD_URL: ${CIRCLE_BUILD_URL}
        BUILD_DATE:   ${BUILD_DATE}
        VCS_REF:      ${VCS_REF}
        APP_VERSION:  ${APP_VERSION}
    read_only: true
    cap_drop:
      - all
    pids_limit: 10
    cpu_shares: 1023
    mem_limit: 1G
    shm_size: 32M
    stdin_open: true
    tty: true

  ssh_scan_tag:
    extends: ssh_scan
    image: jumanjiman/ssh_scan:${TAG}

  scanner:
    extends: ssh_scan
    command: >
      --target 67.205.145.156
      --port   49154
      --policy /etc/ssh_scan/stribika.yml
