#!/bin/sh
set -e

git submodule sync
git submodule update --init

cat > ci/vars <<EOF
export VERSION=$(cd app && git describe --tags --always --dirty)
export BUILD_DATE=$(date +%Y%m%dT%H%M)
export VCS_REF=$(git rev-parse --short HEAD)
export TAG=\${VERSION}_\${BUILD_DATE}_git_\${VCS_REF}
EOF

. ci/vars
docker-compose build
