#!/bin/bash
set -e
set -u
set -o pipefail

################################################################################
# Build image(s). Invoke as "ci/build".
################################################################################
. ci/functions.sh

git submodule sync
git submodule update --init

cat > ci/vars <<EOF
declare -rx APP_VERSION=$(cd app && git describe --tags --always --dirty)
declare -rx BUILD_DATE=$(date +%Y%m%dT%H%M)
declare -rx VCS_REF=$(git rev-parse --short HEAD)
declare -rx TAG=\${APP_VERSION}_\${BUILD_DATE}_git_\${VCS_REF}
EOF

. ci/vars

docker-compose build
