#!/bin/bash
set -e
set -u
set -o pipefail

################################################################################
# Publish image(s). Invoke as "ci/publish".
################################################################################

. ci/vars
. ci/functions.sh

# shellcheck disable=SC2154
docker login -u "${user}" -p "${pass}"
docker-compose push
docker logout

curl -X POST 'https://hooks.microbadger.com/images/jumanjiman/ssh_scan/5rmDLkGXOhL7YSkGyxgg2adCyrA='
