#!/bin/bash
set -e
set -u
set -o pipefail

################################################################################
# Run the test harness. Invoke as "ci/test".
################################################################################

. ci/bootstrap
. ci/vars
. ci/functions.sh

echo
echo Run file checks.
pre-commit run --all-files --verbose

echo
echo Run the scanner against a real host.
docker-compose run --rm scanner
