#!/bin/bash
set -e
set -u
set -o pipefail

################################################################################
# Run the test harness. Invoke as "ci/test".
################################################################################

. ci/vars
. ci/functions.sh

echo
echo Check for things like trailing whitespace.
ci/check-files -d

echo
echo Run the scanner against a real host.
docker-compose run --rm scanner
